# Generated by Django 4.2.4 on 2023-09-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
