# Generated by Django 4.2.4 on 2023-09-02 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_reting_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='author',
        ),
        migrations.RemoveField(
            model_name='like',
            name='game',
        ),
        migrations.RemoveField(
            model_name='reting',
            name='author',
        ),
        migrations.RemoveField(
            model_name='reting',
            name='game',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Reting',
        ),
    ]
